### ISSUE TITLE
Document control is installed but still displays original

### ISSUE THREAD

**Issue by nathanbetters** [ilia-sokolov/PCF-SPFileExplorer#1]
I am using the sharepoint document control and have installed it step by step yet the browser still shows the default document control.

I should note, the only difference is that I am using a custom model app that is backboned off D365, so the entities are the same. We have RapidCRM which is just a slim down version of D365

**Comment by ilia-sokolov** [comment]
Dear Nathan,

Would you be so kind to verify if the SharePoint Full File Explorer is selected for all screen types (step 10 in the installation manual) and if the changes of the view were published.

**Comment by nathanbetters** [comment]
So I think the problem is around the control, it will let me save the new custom control, but then when I exit back to powerapps and then return the custom control is no longer there... Here is a video of all the things I tried
https://www.screencast.com/t/0RMGA3zkwp7i

**Comment by SaltGan** [comment]
Hello, I'm experiencing the same issue. If I navigate through the "Association" tab and then to "Documents", it works and the PCF is indeed visible. However, if I create a "Documents" tab in my model-driven app so as to bypass the "Association" tab, the PCF component is not supported.

Thx

**Comment by ilia-sokolov** [comment]
Thanks a lot for sharing the issue with me. I'll investigate it and come back to you.

**Comment by LeHailender** [comment]
Hi @SaltGan,

please try to assign the PCF component directly in the subgrid of the form 
<img width="600" alt="image" src="https://github.com/ilia-sokolov/PCF-SPFileExplorer/assets/85994794/ce32537f-7ab2-4d6d-82d5-707dd1c74767">

@ilia-sokolov  but then the result looks a little weird ;-)
<img width="600" alt="image" src="https://github.com/ilia-sokolov/PCF-SPFileExplorer/assets/85994794/31efa799-4e71-498f-b047-a9884c46833e">

**Comment by InformedPowerPlatform** [comment]
Following for status. This is an awesome control BTW, thanks for working on it!

I have seen the same thing with the control. If you select Related, Documents it works fine. If you embed a subgrid on a tab and point to the Table "Documents (Regarding)", the only view that shows is the "All Sharepoint Document" view and the page doesn't render correctly.

![2023-09-15_09-06-17](https://github.com/ilia-sokolov/PCF-SPFileExplorer/assets/29958333/a0a295b6-92d3-4e3e-b5d2-2a66ebb5e2fa)

**Comment by ilia-sokolov** [comment]
I have updated the installation manual to cover subgrid scenario.
I have also added a possibility to set minimum height of control to fix the rendering issue.
