### ISSUE TITLE
Documents component is installed but when I change item it show me the documents of previous item

### ISSUE THREAD

**Issue by gbattiato** [ilia-sokolov/PCF-SPFileExplorer#2]
Documents component is installed and working but when I change item it show me the documents of previous item.
if I leave the app and come back it shows me the correct documents.

**Comment by NoonesKN** [comment]
got the same problem

Open Account 1 -> View Account 1
Open Account 2 -> Still Account 1 (FolderPane & Title), shown Files are from Account 2

Reload -> Account 2 is fine, Account 3 shows Account 2 Data

**Comment by ilia-sokolov** [comment]
The issue should be solved now.

**Comment by ilia-sokolov** [comment]
The issue should be solved now.
