### ISSUE TITLE
Location label not changing and explorer tree not updating

### ISSUE THREAD

**Issue by WilsonCrawley** [ilia-sokolov/PCF-SPFileExplorer#3]
I cannot get the explorer tree to populate on load or update when changing document location. The label for the document location does also not change when looking at different document locations (but the files do update).

Default document location on load:

![image](https://github.com/ilia-sokolov/PCF-SPFileExplorer/assets/124005179/2837b087-3650-4d10-8785-6ba49b2146bd)

Changing to "Test Location":

![image](https://github.com/ilia-sokolov/PCF-SPFileExplorer/assets/124005179/aa7a3031-b3db-4c09-b26a-739b09e03df7)

The explorer tree menu doesnt update and the label doesnt change from "Documents on Default Site 1"

**Comment by ilia-sokolov** [comment]
The issue should be fixed now.
