### ISSUE TITLE
special characters inside fetchxml are not handled correctly

### ISSUE THREAD

**Issue by TobiasKoller** [ilia-sokolov/PCF-SPFileExplorer#4]
hi,
when the sharepoint folder contains special characters like & it throws "invalid xml file" on the console and shows nothing.
Using encodeURIComponent is not enough because this is just for the transport to the component which executes the fetchXml.
If the decoded FetchXml contains & it is invalid. You have to replace & with` &amp;` to get a valid xml.

f.e.:

```
function escapeXml(unsafe) {
    return unsafe.replace(/[<>&'"]/g, function (c) {
        switch (c) {
            case '<': return '&lt;';
            case '>': return '&gt;';
            case '&': return '&amp;';
            case '\'': return '&apos;';
            case '"': return '&quot;';
        }
    });
}
```
I think its only a problem on the relativelocation.
`<condition attribute="relativelocation" operator="eq" value="${escapeXml(relativeUrl)}"/>`

**Comment by ilia-sokolov** [comment]
The handling of the special characters has been corrected.
